core/urls.py
from django.urls import path
from core import views as v

app_name = 'core'

urlpatterns =[
	path('', v.index, name='index'),
]

estoque/urls.py
from django.urls import path
from estoque import views as v

app_name = 'estoque'


urlpatterns = [
	path('', v.estoque_entrada_list, name='estoque_entrada_list'),
	path('<int:pk>/', v.estoque_entrada_detail, name='estoque_entrada_detail'),
	path('add/', v.estoque_entrada_add, name='estoque_entrada_add'),
]

produto/urls.py
from django.urls import path
from produto import views as v
# from .views import ProdutoCreate


app_name = 'produto'


urlpatterns = [
	path('', v.produto_list, name='produto_list'),
	path('<int:pk>/', v.produto_detail, name='produto_detail'),
	path('add/', v.ProdutoCreate.as_view(), name='produto_add'),
	path('<int:pk>/edit/', v.ProdutoUpdate.as_view(), name='produto_edit'),
]

projeto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('', include('core.urls')),
	path('produto/', include('produto.urls')),
    path('estoque/', include('estoque.urls')),
    path('admin/', admin.site.urls),
]

core/models.py
from django.db import models


class TimeStampedModel(models.Model):
	created = models.DateTimeField('Criado em', auto_now_add=True, auto_now=False)
	modified = models.DateTimeField('Criado em', auto_now_add=False, auto_now=True)


	class Meta:
		abstract = True

estoque/models.py
from django.db import models
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from core.models import TimeStampedModel
from produto.models import Produto


MOVIMENTO = (
		('e', 'entrada'),
		('s', 'saída'),
	)

class Estoque(TimeStampedModel):
	funcionario = models.ForeignKey(User, on_delete=models.CASCADE)
	nf = models.PositiveIntegerField('nota fiscal', null=True, blank=True)
	movimento = models.CharField(max_length=1, choices=MOVIMENTO)


	class Meta:
		ordering = ('-created',)


	def __str__(self):
		return '{} - {} - {}'.format(self.pk, self.nf, self.created.strftime('%d-%m-%Y'))


	def get_absolute_url(self):
		return reverse_lazy('estoque:estoque_entrada_detail', kwargs={'pk':self.pk})


	def nf_formated(self):
		return str(self.nf).zfill(3)


class EstoqueItens(models.Model):
	estoque = models.ForeignKey(Estoque, on_delete=models.CASCADE, related_name='estoques')
	produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
	quantidade = models.PositiveIntegerField()
	saldo = models.PositiveIntegerField()
		

	class Meta:
		ordering = ('pk',)


	def __str__(self):
		return '{} - {} - {}'.format(self.pk, self.estoque.pk, self.produto)

produto/models.py
from django.db import models
from django.urls import reverse_lazy


class Produto(models.Model):
	importado = models.BooleanField(default=False)
	ncm = models.CharField('NCM', max_length=8)
	produto = models.CharField(max_length=100, unique=True)
	preco = models.DecimalField('Preço', max_digits=7, decimal_places=2)
	estoque = models.IntegerField('Estoque atual')
	estoque_minimo = models.PositiveIntegerField('Estoque mínimo', default=0)


	class Meta:
		ordering = ('produto',)


	def __str__(self):
		return self.produto


	def get_absolute_url(self):
		return reverse_lazy('produto:produto_detail', kwargs={'pk':self.pk})

estoque/forms.py
from django import forms
from .models import Estoque, EstoqueItens


class EstoqueForm(forms.ModelForm):

	class Meta:
		model = Estoque
		fields = '__all__'


class EstoqueItensForm(forms.ModelForm):

	class Meta:
		model = EstoqueItens
		fields = '__all__'
		

produto/forms.py
from django import forms
from .models import Produto


class ProdutoForm(forms.ModelForm):

	class Meta:
		model = Produto
		fields = '__all__'

core/views.py
from django.shortcuts import render


def index(request):
	return render(request, 'index.html')

estoque/views.py
from django.shortcuts import render, resolve_url
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from .models import Estoque, EstoqueItens
from .forms import EstoqueForm, EstoqueItensForm


def estoque_entrada_list(request):
	template_name = 'estoque_entrada_list.html'
	objects = Estoque.objects.filter(movimento='e')
	context = {'object_list':objects}
	return render(request, template_name, context)


def estoque_entrada_detail(request, pk):
	template_name = 'estoque_entrada_detail.html'
	obj = Estoque.objects.get(pk=pk)
	context = {'object':obj}
	return render(request, template_name, context)


def estoque_entrada_add(request):
	template_name = 'estoque_entrada_form.html'
	estoque_form = Estoque()
	item_estoque_formset = inlineformset_factory(
		Estoque,
		EstoqueItens,
		form=EstoqueItensForm,
		extra=0,
		min_num=1,
		validate_min=True,
	)
	if request.method == 'POST':
		form = EstoqueForm(request.POST, instance=estoque_form, prefix='main')
		formset = item_estoque_formset(request.POST, instance=estoque_form, prefix='estoque')
		
		if form.is_valid() and formset.is_valid():
			form = form.save()
			formset.save()
			url = 'estoque:estoque_entrada_detail'
			return HttpResponseRedirect(resolve_url(url, form.pk))
	else:
		form = EstoqueForm(instance=estoque_form, prefix='main')
		formset = item_estoque_formset(instance=estoque_form, prefix='estoque')

	context = {'form': form, 'formset': formset}
	return render(request, template_name, context)

produto/views.py
from django.shortcuts import render
from .models import Produto
from django.views.generic import CreateView, UpdateView
from .forms import ProdutoForm


def produto_list(request):
	template_name = 'produto_list.html'
	objects = Produto.objects.all()
	context = {'object_list':objects}
	return render(request, template_name, context)


def produto_detail(request, pk):
	template_name = 'produto_detail.html'
	obj = Produto.objects.get(pk=pk)
	context = {'object':obj}
	return render(request, template_name, context)


def produto_add(request):
	template_name = 'produto_form.html'
	return render(request, template_name)


class ProdutoCreate(CreateView):
	model = Produto
	template_name = 'produto_form.html'
	form_class = ProdutoForm


class ProdutoUpdate(UpdateView):
	model = Produto
	template_name = 'produto_form.html'
	form_class = ProdutoForm

core/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Controle de Estoque</title>

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

		
		{% block css %}{% endblock css %}
	</head>
	<body>
		{% include "includes/nav.html" %}

		<div class="container">
			{% block content %}{% endblock content %}
		</div>

		<!-- jQuery -->
		<script src="//code.jquery.com/jquery.js"></script>
		<!-- Bootstrap JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
		<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
 		<script src="Hello World"></script>
 		{% block js %}{% endblock js %}
	</body>
</html>

core/templates/includes/nav.html
<nav class="navbar navbar-default" role="navigation">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">Estoque</a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse navbar-ex1-collapse">
			<ul class="nav navbar-nav">
				<li class="active"><a href="{% url 'core:index' %}">Home</a></li>
				<li><a href="{% url 'produto:produto_list' %}">Produtos</a></li>
			</ul>
			
			<ul class="nav navbar-nav">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">Estoque <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><a href="{% url 'estoque:estoque_entrada_list' %}">Entrada</a></li>
						<li><a href="#">Saída</a></li>
					</ul>
				</li>
			</ul>
		</div><!-- /.navbar-collapse -->
	</div>
</nav>

core/templates/index.html
{% extends "base.html" %}

{% block content %}
	<div class="jumbotron">
		<div class="container">
			<h1 class="text-center">Bem-vindo!</h1>
			<p>Este é um sistema para controle de estoque.</p>
		</div>
	</div>
{% endblock content %}

estoque/templates/estoque_entrada_detail.html
{% extends "base.html" %}

{% block content %}
	
	<a href="{% url 'estoque:estoque_entrada_list' %}">Voltar</a>

	<h1>{{ object }}</h1>

	<div class="col-sm-6">
		<table class="table table-user-information">
			<tbody>
				<tr>
					<th class="text-right">NF</th>
					<td>{{ object.nf_formated }}</td>
				</tr>
				<tr>
					<th class="text-right">Data</th>
					<td>{{ object.created }}</td>
				</tr>
				<tr>
					<th class="text-right">Funcionários</th>
					<td>{{ object.funcionario.first_name }}</td>
				</tr>
			</tbody>
		</table>
	</div>

	<table class="table table-striped">
		<thead>
			<tr>
				<td>Produto</td>
				<td>Quantidade</td>
				<td>Saldo</td>
			</tr>
		</thead>
		<tbody>
			{% for obj in object.estoques.all %}
				
				<tr>
					<td>{{ obj.produto }}</td>
					<td>{{ obj.quantidade }}</td>
					<td>{{ obj.saldo }}</td>
				</tr>

			{% endfor %}
		</tbody>
	</table>

{% endblock content %}

estoque/templates/estoque_entrada_form.html
{% extends "base.html" %}

{% load widget_tweaks %}
{% load bootstrap %}

{% block css %}
	<style>
		span.required:after{
			content: "*";
			color: red;
		}
	</style>
{% endblock css %}

{% block content %}
	<a href="{% url 'estoque:estoque_entrada_list' %}">Voltar</a>
	
	<div class="row">
		<div class="cols">
			<form method="POST" novalidate>
				{% csrf_token %}
				<legend style="border-bottom: 1px solid #e5e5e5">Estoque Entrada</legend>

				<div class="row">
					<div class="col-sm-6">
						{% for field in form.visible_fields %}
							<div class="form-group{% if field.errors %} has-error {% endif %}">
								<label for="{{ field.id_for_label }}">
									{% if field.field.required %}
										<span class="required">{{ field.label }} </span>
									{% else %}
										{{ field.label }}
									{% endif %}
								</label>
								{% render_field field class="form-control" %}
								{% for error in field.errors %}
									<span class="text-muted">{{ error }}</span>
								{% endfor %}
							</div>
						{% endfor %}
						{{ formset.management_form }}
					</div>
				</div>
				<div class="row">
					<div class="col-sm-12">
						<legend style="border-bottom: 1px solid #e5e5e5">Produtos</legend>
						<div id="estoque" class="form-inline">
							{% for item_estoque_form in formset %}
								<div id="item-{{ forloop.counter0 }}" class="form-group">
									{{ item_estoque_form|bootstrap }}
								</div>
							{% endfor %}
						</div>
					</div>
				</div>
				<button id="add-item" class="btn btn-info" style="margin-top: 10px;">Adicionar</button>
				<div class="row float-right">
					<div class="col-sm-12" style="margin-top: 10px;">
						<div class="form-inline buttons">
							<button class="btn btn-primary" value="save">Salvar</button>
							<a class="btn btn-danger" href="{% url 'estoque:estoque_entrada_list' %}">Cancelar</a>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
{% endblock content %}


{% block js %}
	<script>
		$(document).ready(function(){
			$('#add-item').click(function(ev){
				ev.preventDefault();
				var count  = $('#estoque').children().length;
				var tmplMarkup = $('#item-estoque').html();
				var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
				$('div#estoque').append(compiledTmpl);

				// Update form count
				$('#id_estoque-TOTAL_FORMS').attr('value', count + 1);

				// Animate the scroll to view our form
				$('html, body').animate({
					scrollTop: $("#add-item").position().top - 200
				}, 800);
			});
		});
	</script>

	<script type="text/html" id="item-estoque">
		<div id="item-__prefix__" class="form-group" style="margin-top: 10px;">
			{{ formset.empty_form|bootstrap }}
		</div>
	</script>
{% endblock js %}

estoque/templates/estoque_entrada_list.html
{% extends "base.html" %}

{% block content %}
	<div class="col-md-12">
		<h2>Estoque Entrada
			<span class="pull-right">
				<a class="btn btn-primary" href="{% url 'estoque:estoque_entrada_add' %}">Adicionar</a>
			</span>
		</h2>

        {% if object_list %}

		<table class="table-striped col-md-12">
			<tr>
				<th>Ítem</th>
				<th>NF</th>
				<th>Data</th>
				<th>Funcionário</th>
			</tr>
			<tbody>
				{% for object in object_list %}
					<tr>
						<td><a href="{% url 'estoque:estoque_entrada_detail' object.pk %}">{{object}}</a></td>
						<td>{{ object.nf_formated }}</td>
						<td>{{ object.created }}</td>
						<td>{{ object.funcionario.first_name }}</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
		
		{% else %}
			<p class="alert alert-warning">Sem ítens na lista!</p>
		{% endif %}
	</div>
{% endblock content %}

produto/templates/produto_detail.html
{% extends "base.html" %}


{% block content %}
	<a href="{% url 'produto:produto_list' %}">Voltar</a>
	<h1>{{object}}
		<span class="pull-right">
			<a href="{% url 'produto:produto_edit' object.pk %}">
				<button type="button" class="btn btn-success">Editar</button>
			</a>
		</span>
	</h1>
	<div class="col-sm-6">
		<table class="table table-user-information">
			<tbody>
				<tr>
					<th class="text-right">Importado</th>
					<td>
						{% if object.importado %}
							<span class="glyphicon glyphicon-ok-sign" style="color: green;"></span>
						{% else %}
							<span class="glyphicon glyphicon-remove-sign" style="color: red;"></span>
						{% endif %}
					</td>
				</tr>
				<tr>
					<th class="text-right">NCM</th>
					<td>{{object.ncm}}</td>
				</tr>
				<tr>
					<th class="text-right">Preço</th>
					<td>R$ {{object.preco}}</td>
				</tr>
				<tr>
					<th class="text-right">Estoque</th>
					<td>{{object.estoque}}</td>
				</tr>
				<tr>
					<th class="text-right">Estoque Mínimo</th>
					<td>{{object.estoque_minimo}}</td>
				</tr>
			</tbody>
		</table>
	</div>
{% endblock content %}

produto/templates/produto_form.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block css %}
	<style>
		span.required:after{
			content: "*";
			color: red;
		}
	</style>
{% endblock css %}

{% block content %}
	<form method="POST">
		{% csrf_token %}
		{% for field in form.visible_fields %}
			<div class="form-group{% if field.errors %} has-error {% endif %}">
				<label for="{{ field.id_for_label }}">
					{% if field.field.required %}
						<span class="required">{{ field.label }} </span>
					{% else %}
						{{ field.label }}
					{% endif %}
				</label>
				{% render_field field class="form-control" %}
				{% for error in field.errors %}
					<span class="text-muted">{{ error }}</span>
				{% endfor %}
			</div>
		{% endfor %}
		<button class="btn btn-success" type="submit">Cadastrar</button>
	</form>
{% endblock content %}

{% block js %}
	<script>
		$('#id_importado').removeClass('form-control');
	</script>
{% endblock js %}

produto/templates/produto_list.html
{% extends "base.html" %}

{% block content %}
	<div class="col-md-12">
		<h2>Lista de Produtos
			<span class="pull-right">
				<a class="btn btn-primary" href="{% url 'produto:produto_add' %}">Adicionar</a>
			</span>
		</h2>

        {% if object_list %}

		<table class="table-striped col-md-12">
			<tr>
				<th>Importado</th>
				<th>NCM</th>
				<th>Produto</th>
				<th class="text-center">Preço</th>
				<th class="text-center">Estoque</th>
				<th class="text-center">Estoque Mínimo</th>
			</tr>
			<tbody>
				{% for object in object_list %}
					<tr>
						<td>
							{% if object.importado %}
								<span class="glyphicon glyphicon-ok-sign" style="color: green;"></span>
							{% else %}
								<span class="glyphicon glyphicon-remove-sign" style="color: red;"></span>
							{% endif %}
						</td>
						<td>{{object.ncm}}</td>
						<td><a href="{% url 'produto:produto_detail' object.pk %}">{{object.produto}}</a></td>
						<td>R$ <span class="pull-right">{{object.preco}}</span></td>
						<td class="text-center">{{object.estoque}}</td>
						<td class="text-center">{{object.estoque_minimo}}</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
		
		{% else %}
			<p class="alert alert-warning">Sem ítens na lista!</p>
		{% endif %}
	</div>
{% endblock content %}